services:
  - type: web
    name: IB-Maths-Stuff
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT --chdir web app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    disk:
      name: ibmath-data
      mountPath: /data
      sizeGB: 1
